### ISSUE TITLE
 bugzilla_docker]# docker-compose build   Error

### ISSUE THREAD

**Issue by nevinhappy** [zenland/bugzilla_docker#1]
clone 出你的这个分支或者是原分支，都出现下输出：
[root@bogon bugzilla_docker]# docker-compose build
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 124, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 41, in project_from_options
    compatibility=options.get('--compatibility'),
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 113, in get_project
    config_data = config.load(config_details, compatibility)
  File "/usr/lib/python2.7/site-packages/compose/config/config.py", line 385, in load
    for config_file in config_details.config_files
  File "/usr/lib/python2.7/site-packages/compose/config/config.py", line 552, in process_config_file
    validate_against_config_schema(config_file)
  File "/usr/lib/python2.7/site-packages/compose/config/validation.py", line 437, in validate_against_config_schema
    config_file.filename)
  File "/usr/lib/python2.7/site-packages/compose/config/validation.py", line 494, in handle_errors
    errors = list(sorted(errors, key=str))
  File "/usr/lib/python2.7/site-packages/jsonschema/validators.py", line 274, in iter_errors
    for error in errors:
  File "/usr/lib/python2.7/site-packages/jsonschema/_validators.py", line 402, in properties
    schema_path=property,
  File "/usr/lib/python2.7/site-packages/jsonschema/validators.py", line 290, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/lib/python2.7/site-packages/jsonschema/validators.py", line 274, in iter_errors
    for error in errors:
  File "/usr/lib/python2.7/site-packages/jsonschema/_validators.py", line 16, in patternProperties
    v, subschema, path=k, schema_path=pattern,
  File "/usr/lib/python2.7/site-packages/jsonschema/validators.py", line 290, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/lib/python2.7/site-packages/jsonschema/validators.py", line 274, in iter_errors
    for error in errors:
  File "/usr/lib/python2.7/site-packages/jsonschema/_validators.py", line 310, in ref
    scope, resolved = validator.resolver.resolve(ref)
  File "/usr/lib/python2.7/site-packages/jsonschema/validators.py", line 655, in resolve
    return url, self._remote_cache(url)
  File "/usr/lib/python2.7/site-packages/functools32/functools32.py", line 400, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/lib/python2.7/site-packages/jsonschema/validators.py", line 665, in resolve_from_url
    raise RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: addinfourl instance has no attribute '__exit__'

**Comment by nevinhappy** [comment]
> clone 出你的这个分支或者是原分支，都出现下输出：
> [root@bogon bugzilla_docker]# docker-compose build
> Traceback (most recent call last):
> File "/usr/bin/docker-compose", line 11, in 
> sys.exit(main())
> File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 71, in main
> command()
> File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 124, in perform_command
> project = project_from_options('.', options)
> File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 41, in project_from_options
> compatibility=options.get('--compatibility'),
> File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 113, in get_project
> config_data = config.load(config_details, compatibility)
> File "/usr/lib/python2.7/site-packages/compose/config/config.py", line 385, in load
> for config_file in config_details.config_files
> File "/usr/lib/python2.7/site-packages/compose/config/config.py", line 552, in process_config_file
> validate_against_config_schema(config_file)
> File "/usr/lib/python2.7/site-packages/compose/config/validation.py", line 437, in validate_against_config_schema
> config_file.filename)
> File "/usr/lib/python2.7/site-packages/compose/config/validation.py", line 494, in handle_errors
> errors = list(sorted(errors, key=str))
> File "/usr/lib/python2.7/site-packages/jsonschema/validators.py", line 274, in iter_errors
> for error in errors:
> File "/usr/lib/python2.7/site-packages/jsonschema/_validators.py", line 402, in properties
> schema_path=property,
> File "/usr/lib/python2.7/site-packages/jsonschema/validators.py", line 290, in descend
> for error in self.iter_errors(instance, schema):
> File "/usr/lib/python2.7/site-packages/jsonschema/validators.py", line 274, in iter_errors
> for error in errors:
> File "/usr/lib/python2.7/site-packages/jsonschema/_validators.py", line 16, in patternProperties
> v, subschema, path=k, schema_path=pattern,
> File "/usr/lib/python2.7/site-packages/jsonschema/validators.py", line 290, in descend
> for error in self.iter_errors(instance, schema):
> File "/usr/lib/python2.7/site-packages/jsonschema/validators.py", line 274, in iter_errors
> for error in errors:
> File "/usr/lib/python2.7/site-packages/jsonschema/_validators.py", line 310, in ref
> scope, resolved = validator.resolver.resolve(ref)
> File "/usr/lib/python2.7/site-packages/jsonschema/validators.py", line 655, in resolve
> return url, self._remote_cache(url)
> File "/usr/lib/python2.7/site-packages/functools32/functools32.py", line 400, in wrapper
> result = user_function(*args, **kwds)
> File "/usr/lib/python2.7/site-packages/jsonschema/validators.py", line 665, in resolve_from_url
> raise RefResolutionError(exc)
> jsonschema.exceptions.RefResolutionError: addinfourl instance has no attribute '**exit**'

从另外一个问题找到了原因，可能是docker-compose 版本问题， 在我本地更新了pip 程序后，重新安装docker-compose 可以正常使用。
